name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://lab.ssafy.com/s05-blockchain/S05P21A501"
        env:
          GITLAB_HOSTNAME: "lab.ssafy.com"
          GITLAB_USERNAME: "mirroringGitlabtoGithub"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "63249"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

